version: '3'
services:
  app:
    image: leonid27/owl-bot:latest
    container_name: OwlBot
    volumes:
      - ./config.py:/app/config.py
      - ./users.db:/app/users.db
    environment:
      - DATABASE_URL=sqlite:///app/users.db
      - TZ=Europe/Moscow
