version: '3.8'

services:
  owlbot:
    image: leonid27/owl-bot:latest
    volumes:
      - ./tg.key:/app/tg.key:z
      - ./schedule_cache:/app/schedule_cache:z
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Moscow
    restart: unless-stopped