version: '3.8'

services:
  owlbot:
    image: leonid27/owl-bot:latest
    volumes:
      - ./tg.key:/app/tg.key
      - ./schedule_cache:/app/schedule_cache
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped